In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits= load_digits()

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

TypeError: Invalid parameters passed: {'solver': 'lbfgs'}

In [9]:
# LINEAR REGRESSION
lr = LogisticRegression(solver='lbfgs',multi_class='auto',max_iter=5000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

# kept getting 'lbfgs' failed to converge, increase the number of iterations. even at 500. at 5000, not getting warning anymore

0.9703703703703703

In [12]:
# SVM
svm=SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)
# was getting similar warning about gamma. 

0.40925925925925927

In [13]:
# RANDOM FOREST
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9666666666666667

In [15]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [16]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [17]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [20]:
get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test)

0.40925925925925927

In [22]:
get_score((LogisticRegression(solver='lbfgs',multi_class='auto',max_iter=5000)),X_train,X_test,y_train,y_test)

0.9703703703703703

In [ ]:
getRandomForestClassifier(n_estimators=40)