In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits= load_digits()

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

TypeError: Invalid parameters passed: {'solver': 'lbfgs'}

In [9]:
# LINEAR REGRESSION
lr = LogisticRegression(solver='lbfgs',multi_class='auto',max_iter=5000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

# kept getting 'lbfgs' failed to converge, increase the number of iterations. even at 500. at 5000, not getting warning anymore

0.9703703703703703

In [12]:
# SVM
svm=SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)
# was getting similar warning about gamma. 

0.40925925925925927

In [13]:
# RANDOM FOREST
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9666666666666667

In [15]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [16]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [17]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [20]:
get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test)

0.40925925925925927

In [22]:
get_score((LogisticRegression(solver='lbfgs',multi_class='auto',max_iter=5000)),X_train,X_test,y_train,y_test)

0.9703703703703703

In [23]:
get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test)

0.9685185185185186

In [24]:
from sklearn.model_selection import StratifiedKFold 
folds = StratifiedKFold(n_splits=3)


In [31]:
scors_1=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    print(get_score(LogisticRegression(solver='lbfgs',multi_class='auto',max_iter=5000),X_train,X_test,y_train,y_test))
    print(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
    print(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))
    

0.9282136894824707
0.41068447412353926
0.9315525876460768
0.9415692821368948
0.41569282136894825
0.9415692821368948
0.9165275459098498
0.4273789649415693
0.9148580968280468


In [33]:
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='lbfgs',multi_class='auto',max_iter=5000),X_train,X_test,y_train,y_test))
    scores_svm.apped(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))
    

AttributeError: 'list' object has no attribute 'apped'